shock_params:  
  lambda_t: 0.02
  magnitudes:
    beta_m: 2.3
    m_min: 5
    m_max: 8
  locations:
    x_min: 0
    x_max: 10
    y_min: 0
    y_max: 10
  pgas:
    b1_hat: 0.441
    b2: 0.527
    b5: -0.778
    h: 5.57
  fragilities:
    theta_mat:  [[0.24, 0.45, 0.9], [None, 0.24, 0.675], [None, None, 0.24]]
    sigma: 0.64
dynamic: True # if set to true, box for shocks calculated based on node positions*factor
factor: 0.2 # make box 20% larger in every dimension
