general:
  max_timesteps: 50
model:
  include:
    path: "./model/model_defaults.yaml"
network:
  traffic_assignment:
    max_iterations: 15
    convergence_threshold: 0.01
    update_weight: 0.5
  graph:
    type: "list"
    nodes:
      - id: 0
        position_x: 0
        position_y: 0
      - id: 1
        position_x: 0
        position_y: 1
      - id: 2
        position_x: 1
        position_y: 0
      - id: 3
        position_x: 1
        position_y: 1
    edges:
      - id: 0
        source: 0
        target: 1
        distance: 1
      - id: 1
        source: 1
        target: 3
        distance: 1
      - id: 2
        source: 2
        target: 0
        distance: 1
      - id: 3
        source: 3
        target: 2
        distance: 1
  trips:     
    type: "list"
    list:
      - origin: 0
        destination: 1
        volume: 200
      - origin: 1
        destination: 3
        volume: 200
      - origin: 2
        destination: 0
        volume: 200
      - origin: 3
        destination: 2
        volume: 200
  segments: 
    type: "list"
    list:
      - source: 0
        target: 1
        capacity: 500
        travel_time: 50
        position_x: 0
        position_y: 0.33
      - source: 0
        target: 1
        capacity: 500
        travel_time: 50
        position_x: 0.66
        position_y: 0
      - source: 1
        target: 3
        capacity: 500
        travel_time: 50
        position_x: 0.33
        position_y: 1
      - source: 1
        target: 3
        capacity: 500
        travel_time: 50
        position_x: 1
        position_y: 0.66
      - source: 2
        target: 0
        capacity: 500
        travel_time: 50
        position_x: 0
        position_y: 0.33
      - source: 2
        target: 0
        capacity: 500
        travel_time: 50
        position_x: 0
        position_y: 0.66
      - source: 3
        target: 2
        capacity: 500
        travel_time: 50
        position_x: 1
        position_y: 0.33
      - source: 3
        target: 2
        capacity: 500
        travel_time: 50
        position_x: 0.66
        position_y: 1
