general:
  max_timesteps: 50
model:
  include:
    path: "./model/model_defaults.yaml"
  initial_damage_state_proxy: [0.6, 0.134, 0.133, 0.133 ,0]
network:
  include:
    path: "./countries/BE/network.yaml"
  
