general:
  max_timesteps: 50
model:
  include:
    path: "./model/model_defaults.yaml"
  initial_damage_prob: [0.55, 0.15, 0.15, 0.15 ,0]
network:
  include:
    path: "./countries/ME/network.yaml"
  
