general:
  max_timesteps: 50
model:
  include:
    path: "./model/model_defaults.yaml"
    override: False
  segment:
    initial_damage_distribution: [0.6, 0.134, 0.133, 0.133 ,0]
network:
  include:
    path: "./countries/BE/network.yaml"
  
