general:
  max_timesteps: 50
model:
  include:
    path: "./model/model_nonstationary.yaml"
    override: False
  segment:
    initial_damage_distribution: [0.55, 0.15, 0.15, 0.15 ,0]
  network:
    travel_time_reward_factor: -50000.0
network:
  include:
    path: "./countries/ME/network.yaml"
