general:
  max_timesteps: 50
model:
  include:
    path: "./model/model_nonstationary.yaml"
    override: False
  segment:
    initial_damage_distribution: [1, 0.0, 0.0, 0.0 ,0]
  network:
    travel_time_reward_factor: -100000.0
network:
  traffic_assignment:
    max_iterations: 15
    convergence_threshold: 0.01
    update_weight: 0.1
  graph:
    type: "list"
    nodes:
      - id: 0
        position_x: 0
        position_y: 0
      - id: 1
        position_x: 0
        position_y: 1
      - id: 2
        position_x: 0
        position_y: 2
      - id: 3
        position_x: 1
        position_y: 2
      - id: 4
        position_x: 1
        position_y: 1
      - id: 5
        position_x: 1
        position_y: 0
    edges:
      - id: 0
        source: 0
        target: 1
        distance: 1
      - id: 1
        source: 1
        target: 2
        distance: 1
      - id: 2
        source: 2
        target: 3
        distance: 1
      - id: 3
        source: 3
        target: 4
        distance: 1
      - id: 4
        source: 4
        target: 5
        distance: 1
      - id: 5
        source: 1
        target: 4
        distance: 1
  trips:     
    type: "list"
    list:
      - origin: 0
        destination: 2
        volume: 45
      - origin: 0
        destination: 3
        volume: 45
      - origin: 5
        destination: 3
        volume: 45
      - origin: 5
        destination: 2
        volume: 45
  segments: 
    type: "list"
    list:
      - source: 0
        target: 1
        capacity: 100
        travel_time: 1
        position_x: 0
        position_y: 0.5
      - source: 1
        target: 2
        capacity: 100
        travel_time: 1
        position_x: 0
        position_y: 1.5
      - source: 2
        target: 3
        capacity: 100
        travel_time: 1
        position_x: 0.5
        position_y: 2
      - source: 3
        target: 4
        capacity: 100
        travel_time: 1
        position_x: 1
        position_y: 1.5
      - source: 4
        target: 5
        capacity: 100
        travel_time: 1
        position_x: 1
        position_y: 0.5
      - source: 1
        target: 4
        capacity: 100
        travel_time: 1
        position_x: 0.5
        position_y: 1


  
